[2023-05-17T14:28:14.015+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV5.fo manual__2023-05-17T14:20:25.124819+00:00 [queued]>
[2023-05-17T14:28:14.115+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV5.fo manual__2023-05-17T14:20:25.124819+00:00 [queued]>
[2023-05-17T14:28:14.116+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T14:28:14.116+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-05-17T14:28:14.116+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T14:28:14.500+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fo> on 2023-05-17 14:20:25.124819+00:00
[2023-05-17T14:28:14.505+0000] {standard_task_runner.py:55} INFO - Started process 11164 to run task
[2023-05-17T14:28:14.531+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_third_dagV5', 'fo', 'manual__2023-05-17T14:20:25.124819+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpfknsab9p']
[2023-05-17T14:28:14.532+0000] {standard_task_runner.py:83} INFO - Job 173: Subtask fo
[2023-05-17T14:28:14.706+0000] {task_command.py:388} INFO - Running <TaskInstance: my_third_dagV5.fo manual__2023-05-17T14:20:25.124819+00:00 [running]> on host 031cfb56e8fb
[2023-05-17T14:28:15.349+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_third_dagV5
AIRFLOW_CTX_TASK_ID=fo
AIRFLOW_CTX_EXECUTION_DATE=2023-05-17T14:20:25.124819+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-17T14:20:25.124819+00:00
[2023-05-17T14:29:35.916+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
  warnings.warn("Python 3.7 support is deprecated in Spark 3.4.", FutureWarning)

[2023-05-17T14:29:36.063+0000] {logging_mixin.py:137} INFO - Hello
[2023-05-17T14:29:36.063+0000] {logging_mixin.py:137} INFO - <pyspark.sql.session.SparkSession object at 0x7fd6c3e68b90>
[2023-05-17T14:29:36.063+0000] {logging_mixin.py:137} INFO - Bye
[2023-05-17T14:29:42.019+0000] {logging_mixin.py:137} INFO - 0
[2023-05-17T14:29:48.806+0000] {logging_mixin.py:137} INFO - <class 'pyspark.sql.dataframe.DataFrame'>
[2023-05-17T14:29:50.481+0000] {logging_mixin.py:137} INFO - 1.674352211999576
[2023-05-17T14:29:50.485+0000] {logging_mixin.py:137} INFO - 1
[2023-05-17T14:29:52.686+0000] {logging_mixin.py:137} INFO - <class 'pyspark.sql.dataframe.DataFrame'>
[2023-05-17T14:29:53.482+0000] {logging_mixin.py:137} INFO - 0.7965465699999186
[2023-05-17T14:29:53.485+0000] {logging_mixin.py:137} INFO - 2
[2023-05-17T14:29:55.642+0000] {logging_mixin.py:137} INFO - <class 'pyspark.sql.dataframe.DataFrame'>
[2023-05-17T14:29:56.337+0000] {logging_mixin.py:137} INFO - 0.6948189499998989
[2023-05-17T14:29:56.340+0000] {logging_mixin.py:137} INFO - 3
[2023-05-17T14:29:58.170+0000] {logging_mixin.py:137} INFO - <class 'pyspark.sql.dataframe.DataFrame'>
[2023-05-17T14:29:59.061+0000] {logging_mixin.py:137} INFO - 0.891832097000588
[2023-05-17T14:29:59.065+0000] {logging_mixin.py:137} INFO - 4
[2023-05-17T14:30:03.560+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag3.py", line 281, in foo1
    h_vec = print_return_lin_hypothesisies(df_binary)
  File "/opt/airflow/dags/dag3.py", line 134, in print_return_lin_hypothesisies
    k_err, b_err = summary.coefficientStandardErrors
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/ml/regression.py", line 2935, in coefficientStandardErrors
    return self._call_java("coefficientStandardErrors")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/ml/wrapper.py", line 72, in _call_java
    return _java2py(sc, m(*java_args))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1323, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/errors/exceptions/captured.py", line 169, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o744.coefficientStandardErrors.
: java.lang.UnsupportedOperationException: No Std. Error of coefficients available for this GeneralizedLinearRegressionModel
	at org.apache.spark.ml.regression.GeneralizedLinearRegressionTrainingSummary.coefficientStandardErrors$lzycompute(GeneralizedLinearRegression.scala:1467)
	at org.apache.spark.ml.regression.GeneralizedLinearRegressionTrainingSummary.coefficientStandardErrors(GeneralizedLinearRegression.scala:1462)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)

[2023-05-17T14:30:03.690+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_third_dagV5, task_id=fo, execution_date=20230517T142025, start_date=20230517T142814, end_date=20230517T143003
[2023-05-17T14:30:03.703+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 173 for task fo (An error occurred while calling o744.coefficientStandardErrors.
: java.lang.UnsupportedOperationException: No Std. Error of coefficients available for this GeneralizedLinearRegressionModel
	at org.apache.spark.ml.regression.GeneralizedLinearRegressionTrainingSummary.coefficientStandardErrors$lzycompute(GeneralizedLinearRegression.scala:1467)
	at org.apache.spark.ml.regression.GeneralizedLinearRegressionTrainingSummary.coefficientStandardErrors(GeneralizedLinearRegression.scala:1462)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
; 11164)
[2023-05-17T14:30:03.756+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-17T14:30:03.769+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
