[2023-01-31T11:33:37.885+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV6.insert_task manual__2023-01-31T11:33:33.634332+00:00 [queued]>
[2023-01-31T11:33:37.894+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV6.insert_task manual__2023-01-31T11:33:33.634332+00:00 [queued]>
[2023-01-31T11:33:37.894+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T11:33:37.895+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-31T11:33:37.895+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T11:33:37.906+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_task> on 2023-01-31 11:33:33.634332+00:00
[2023-01-31T11:33:37.909+0000] {standard_task_runner.py:55} INFO - Started process 228 to run task
[2023-01-31T11:33:37.912+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV6', 'insert_task', 'manual__2023-01-31T11:33:33.634332+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpp4phgc1h']
[2023-01-31T11:33:37.912+0000] {standard_task_runner.py:83} INFO - Job 32: Subtask insert_task
[2023-01-31T11:33:37.987+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV6.insert_task manual__2023-01-31T11:33:33.634332+00:00 [running]> on host 7630aa9dbd23
[2023-01-31T11:33:38.067+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV6
AIRFLOW_CTX_TASK_ID=insert_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-31T11:33:33.634332+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-31T11:33:33.634332+00:00
[2023-01-31T11:33:38.068+0000] {sql.py:254} INFO - Executing: 
            insert into tutor VALUES (default, "Starkov", "dag_id")
        
[2023-01-31T11:33:38.076+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-31T11:33:38.289+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-31T11:33:38.292+0000] {sql.py:375} INFO - Running statement: 
            insert into tutor VALUES (default, "Starkov", "dag_id")
        , parameters: None
[2023-01-31T11:33:38.293+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "Starkov" does not exist
LINE 2:             insert into tutor VALUES (default, "Starkov", "d...
                                                       ^

[2023-01-31T11:33:38.301+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_second_dagV6, task_id=insert_task, execution_date=20230131T113333, start_date=20230131T113337, end_date=20230131T113338
[2023-01-31T11:33:38.315+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 32 for task insert_task (column "Starkov" does not exist
LINE 2:             insert into tutor VALUES (default, "Starkov", "d...
                                                       ^
; 228)
[2023-01-31T11:33:38.328+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-31T11:33:38.345+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
