[2023-01-31T11:36:15.230+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV6.insert_task manual__2023-01-31T11:33:33.634332+00:00 [queued]>
[2023-01-31T11:36:15.240+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV6.insert_task manual__2023-01-31T11:33:33.634332+00:00 [queued]>
[2023-01-31T11:36:15.241+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T11:36:15.241+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-01-31T11:36:15.241+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T11:36:15.253+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_task> on 2023-01-31 11:33:33.634332+00:00
[2023-01-31T11:36:15.257+0000] {standard_task_runner.py:55} INFO - Started process 425 to run task
[2023-01-31T11:36:15.260+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV6', 'insert_task', 'manual__2023-01-31T11:33:33.634332+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpfg1o5mnp']
[2023-01-31T11:36:15.260+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask insert_task
[2023-01-31T11:36:15.395+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV6.insert_task manual__2023-01-31T11:33:33.634332+00:00 [running]> on host 7630aa9dbd23
[2023-01-31T11:36:15.526+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV6
AIRFLOW_CTX_TASK_ID=insert_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-31T11:33:33.634332+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-31T11:33:33.634332+00:00
[2023-01-31T11:36:15.527+0000] {sql.py:254} INFO - Executing: 
            insert into tutor (tutor_id, name, speciality) VALUES (default, "Starkov", "dag_id")
        
[2023-01-31T11:36:15.549+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-31T11:36:15.763+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-31T11:36:15.768+0000] {sql.py:375} INFO - Running statement: 
            insert into tutor (tutor_id, name, speciality) VALUES (default, "Starkov", "dag_id")
        , parameters: None
[2023-01-31T11:36:15.770+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "Starkov" does not exist
LINE 2: ...tor (tutor_id, name, speciality) VALUES (default, "Starkov",...
                                                             ^

[2023-01-31T11:36:15.783+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_second_dagV6, task_id=insert_task, execution_date=20230131T113333, start_date=20230131T113615, end_date=20230131T113615
[2023-01-31T11:36:15.817+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task insert_task (column "Starkov" does not exist
LINE 2: ...tor (tutor_id, name, speciality) VALUES (default, "Starkov",...
                                                             ^
; 425)
[2023-01-31T11:36:15.836+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-31T11:36:15.859+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
