[2023-02-01T18:57:19.707+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo manual__2023-02-01T18:57:13.777473+00:00 [queued]>
[2023-02-01T18:57:19.769+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo manual__2023-02-01T18:57:13.777473+00:00 [queued]>
[2023-02-01T18:57:19.769+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-01T18:57:19.769+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-01T18:57:19.769+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-01T18:57:19.781+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fo> on 2023-02-01 18:57:13.777473+00:00
[2023-02-01T18:57:19.785+0000] {standard_task_runner.py:55} INFO - Started process 15600 to run task
[2023-02-01T18:57:19.788+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_third_dagV1', 'fo', 'manual__2023-02-01T18:57:13.777473+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpvrql6o1_']
[2023-02-01T18:57:19.788+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask fo
[2023-02-01T18:57:19.859+0000] {task_command.py:388} INFO - Running <TaskInstance: my_third_dagV1.fo manual__2023-02-01T18:57:13.777473+00:00 [running]> on host 47e55e08a495
[2023-02-01T18:57:19.953+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_third_dagV1
AIRFLOW_CTX_TASK_ID=fo
AIRFLOW_CTX_EXECUTION_DATE=2023-02-01T18:57:13.777473+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-01T18:57:13.777473+00:00
[2023-02-01T18:57:34.510+0000] {logging_mixin.py:137} INFO - Empty DataFrame
Columns: []
Index: []
[2023-02-01T18:57:34.514+0000] {logging_mixin.py:137} INFO - Ошибка при работе с PostgreSQL name 'sql' is not defined
[2023-02-01T18:57:34.514+0000] {logging_mixin.py:137} INFO - Соединение с PostgreSQL закрыто
[2023-02-01T18:57:34.515+0000] {python.py:177} INFO - Done. Returned value was: 2
[2023-02-01T18:57:34.554+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_third_dagV1, task_id=fo, execution_date=20230201T185713, start_date=20230201T185719, end_date=20230201T185734
[2023-02-01T18:57:34.613+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-01T18:57:34.628+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
