[2023-01-31T22:00:41.007+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo manual__2023-01-31T21:54:08.332164+00:00 [queued]>
[2023-01-31T22:00:41.016+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo manual__2023-01-31T21:54:08.332164+00:00 [queued]>
[2023-01-31T22:00:41.017+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T22:00:41.017+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 3
[2023-01-31T22:00:41.017+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T22:00:41.028+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fo> on 2023-01-31 21:54:08.332164+00:00
[2023-01-31T22:00:41.032+0000] {standard_task_runner.py:55} INFO - Started process 780 to run task
[2023-01-31T22:00:41.034+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_third_dagV1', 'fo', 'manual__2023-01-31T21:54:08.332164+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpb1_gavib']
[2023-01-31T22:00:41.035+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask fo
[2023-01-31T22:00:41.129+0000] {task_command.py:388} INFO - Running <TaskInstance: my_third_dagV1.fo manual__2023-01-31T21:54:08.332164+00:00 [running]> on host 47e55e08a495
[2023-01-31T22:00:41.208+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_third_dagV1
AIRFLOW_CTX_TASK_ID=fo
AIRFLOW_CTX_EXECUTION_DATE=2023-01-31T21:54:08.332164+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-31T21:54:08.332164+00:00
[2023-01-31T22:00:42.190+0000] {logging_mixin.py:137} INFO - Empty DataFrame
Columns: []
Index: []
[2023-01-31T22:00:42.193+0000] {logging_mixin.py:137} INFO - Вы подключены к -  ('PostgreSQL 13.9 (Debian 13.9-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit',) 
[2023-01-31T22:00:42.193+0000] {logging_mixin.py:137} INFO - Соединение с PostgreSQL закрыто
[2023-01-31T22:00:42.193+0000] {python.py:177} INFO - Done. Returned value was: 2
[2023-01-31T22:00:42.251+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_third_dagV1, task_id=fo, execution_date=20230131T215408, start_date=20230131T220041, end_date=20230131T220042
[2023-01-31T22:00:42.295+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-31T22:00:42.312+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
