[2023-05-17T13:51:27.612+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV5.fo manual__2023-05-17T13:51:26.483257+00:00 [queued]>
[2023-05-17T13:51:27.638+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV5.fo manual__2023-05-17T13:51:26.483257+00:00 [queued]>
[2023-05-17T13:51:27.638+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T13:51:27.638+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-05-17T13:51:27.638+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T13:51:27.650+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fo> on 2023-05-17 13:51:26.483257+00:00
[2023-05-17T13:51:27.655+0000] {standard_task_runner.py:55} INFO - Started process 7772 to run task
[2023-05-17T13:51:27.659+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_third_dagV5', 'fo', 'manual__2023-05-17T13:51:26.483257+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpc297vebz']
[2023-05-17T13:51:27.659+0000] {standard_task_runner.py:83} INFO - Job 169: Subtask fo
[2023-05-17T13:51:27.722+0000] {task_command.py:388} INFO - Running <TaskInstance: my_third_dagV5.fo manual__2023-05-17T13:51:26.483257+00:00 [running]> on host 031cfb56e8fb
[2023-05-17T13:51:27.838+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_third_dagV5
AIRFLOW_CTX_TASK_ID=fo
AIRFLOW_CTX_EXECUTION_DATE=2023-05-17T13:51:26.483257+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-17T13:51:26.483257+00:00
[2023-05-17T13:51:40.600+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
  warnings.warn("Python 3.7 support is deprecated in Spark 3.4.", FutureWarning)

[2023-05-17T13:51:40.732+0000] {logging_mixin.py:137} INFO - Hello
[2023-05-17T13:51:40.732+0000] {logging_mixin.py:137} INFO - <pyspark.sql.session.SparkSession object at 0x7fd6b710bdd0>
[2023-05-17T13:51:40.732+0000] {logging_mixin.py:137} INFO - Bye
[2023-05-17T13:51:46.195+0000] {logging_mixin.py:137} INFO - 0
[2023-05-17T13:51:52.644+0000] {logging_mixin.py:137} INFO - <class 'pyspark.sql.dataframe.DataFrame'>
[2023-05-17T13:51:53.140+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2023-05-17T13:51:53.140+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/serializers.py", line 459, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
[2023-05-17T13:51:53.140+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
[2023-05-17T13:51:53.140+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 819, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 756, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2023-05-17T13:51:53.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
[2023-05-17T13:51:53.142+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2023-05-17T13:51:53.142+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/dill/_dill.py", line 1146, in save_cell
    f = obj.cell_contents
[2023-05-17T13:51:53.142+0000] {logging_mixin.py:137} WARNING - ValueError: Cell is empty
[2023-05-17T13:51:53.143+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/serializers.py", line 459, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
  File "/usr/local/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 819, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 756, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
  File "/usr/local/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/airflow/.local/lib/python3.7/site-packages/dill/_dill.py", line 1146, in save_cell
    f = obj.cell_contents
ValueError: Cell is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag3.py", line 282, in foo1
    optimization_reinforced_learning(df_binary, h_vec)
  File "/opt/airflow/dags/dag3.py", line 181, in optimization_reinforced_learning
    print(df_binary.select("sales_amount").rdd.flatMap(lambda x: x).collect())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/rdd.py", line 1814, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/rdd.py", line 5442, in _jrdd
    self.ctx, self.func, self._prev_jrdd_deserializer, self._jrdd_deserializer, profiler
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/rdd.py", line 5241, in _wrap_function
    pickled_command, broadcast_vars, env, includes = _prepare_for_python_RDD(sc, command)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/rdd.py", line 5224, in _prepare_for_python_RDD
    pickled_command = ser.dumps(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/serializers.py", line 469, in dumps
    raise pickle.PicklingError(msg)
_pickle.PicklingError: Could not serialize object: ValueError: Cell is empty
[2023-05-17T13:51:53.151+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_third_dagV5, task_id=fo, execution_date=20230517T135126, start_date=20230517T135127, end_date=20230517T135153
[2023-05-17T13:51:53.268+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 169 for task fo (Could not serialize object: ValueError: Cell is empty; 7772)
[2023-05-17T13:51:53.299+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-17T13:51:53.314+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
