[2023-01-30T14:11:12.598+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-01-30T14:11:12.607+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-01-30T14:11:12.607+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T14:11:12.607+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-30T14:11:12.607+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T14:11:12.639+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fo> on 2023-01-22 00:00:00+00:00
[2023-01-30T14:11:12.643+0000] {standard_task_runner.py:55} INFO - Started process 575 to run task
[2023-01-30T14:11:12.651+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_third_dagV1', 'fo', 'scheduled__2023-01-22T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpeyf6ow6l']
[2023-01-30T14:11:12.652+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask fo
[2023-01-30T14:11:12.713+0000] {task_command.py:388} INFO - Running <TaskInstance: my_third_dagV1.fo scheduled__2023-01-22T00:00:00+00:00 [running]> on host 7b03a031af5e
[2023-01-30T14:11:12.783+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_third_dagV1
AIRFLOW_CTX_TASK_ID=fo
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-22T00:00:00+00:00
[2023-01-30T14:11:13.571+0000] {logging_mixin.py:137} INFO - Empty DataFrame
Columns: []
Index: []
[2023-01-30T14:11:13.571+0000] {python.py:177} INFO - Done. Returned value was: 2
[2023-01-30T14:11:13.820+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_third_dagV1, task_id=fo, execution_date=20230122T000000, start_date=20230130T141112, end_date=20230130T141113
[2023-01-30T14:11:13.864+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-30T14:11:13.882+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-31T09:26:24.785+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-01-31T09:26:24.832+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-01-31T09:26:24.833+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T09:26:24.833+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-31T09:26:24.833+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T09:26:24.876+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fo> on 2023-01-22 00:00:00+00:00
[2023-01-31T09:26:24.882+0000] {standard_task_runner.py:55} INFO - Started process 2458 to run task
[2023-01-31T09:26:24.888+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_third_dagV1', 'fo', 'scheduled__2023-01-22T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpbh1evdnx']
[2023-01-31T09:26:24.889+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask fo
[2023-01-31T09:26:24.985+0000] {task_command.py:388} INFO - Running <TaskInstance: my_third_dagV1.fo scheduled__2023-01-22T00:00:00+00:00 [running]> on host ab5131891604
[2023-01-31T09:26:25.124+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_third_dagV1
AIRFLOW_CTX_TASK_ID=fo
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-22T00:00:00+00:00
[2023-01-31T09:26:29.767+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag3.py", line 21, in foo1
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-01-31T09:26:29.810+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_third_dagV1, task_id=fo, execution_date=20230122T000000, start_date=20230131T092624, end_date=20230131T092629
[2023-01-31T09:26:29.830+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 23 for task fo (No module named 'matplotlib'; 2458)
[2023-01-31T09:26:29.885+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-31T09:26:29.946+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
