[2023-01-28T10:01:50.867+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV4.insert_task manual__2023-01-28T10:00:18.485978+00:00 [queued]>
[2023-01-28T10:01:50.886+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV4.insert_task manual__2023-01-28T10:00:18.485978+00:00 [queued]>
[2023-01-28T10:01:50.886+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T10:01:50.886+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-01-28T10:01:50.886+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T10:01:50.996+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_task> on 2023-01-28 10:00:18.485978+00:00
[2023-01-28T10:01:51.002+0000] {standard_task_runner.py:55} INFO - Started process 10684 to run task
[2023-01-28T10:01:51.005+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV4', 'insert_task', 'manual__2023-01-28T10:00:18.485978+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp7jv5cr8q']
[2023-01-28T10:01:51.005+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask insert_task
[2023-01-28T10:01:51.201+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV4.insert_task manual__2023-01-28T10:00:18.485978+00:00 [running]> on host 9763ece73850
[2023-01-28T10:01:51.333+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV4
AIRFLOW_CTX_TASK_ID=insert_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-28T10:00:18.485978+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-28T10:00:18.485978+00:00
[2023-01-28T10:01:51.334+0000] {sql.py:254} INFO - Executing: 
            insert into dag_runs(dt, dag_id) VALUES (%(ds)s, 'dag is dag not a dag22')
        
[2023-01-28T10:01:51.342+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T10:01:51.529+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T10:01:51.532+0000] {sql.py:375} INFO - Running statement: 
            insert into dag_runs(dt, dag_id) VALUES (%(ds)s, 'dag is dag not a dag22')
        , parameters: {'ds': datetime.datetime(2022, 2, 10, 0, 0)}
[2023-01-28T10:01:51.533+0000] {sql.py:384} INFO - Rows affected: 1
[2023-01-28T10:01:51.585+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_second_dagV4, task_id=insert_task, execution_date=20230128T100018, start_date=20230128T100150, end_date=20230128T100151
[2023-01-28T10:01:51.659+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-28T10:01:51.674+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
