[2023-01-28T07:44:26.743+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV3.insert_task manual__2023-01-28T07:43:54.790521+00:00 [queued]>
[2023-01-28T07:44:26.814+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV3.insert_task manual__2023-01-28T07:43:54.790521+00:00 [queued]>
[2023-01-28T07:44:26.814+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T07:44:26.814+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-28T07:44:26.815+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T07:44:26.931+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_task> on 2023-01-28 07:43:54.790521+00:00
[2023-01-28T07:44:26.938+0000] {standard_task_runner.py:55} INFO - Started process 5930 to run task
[2023-01-28T07:44:26.943+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV3', 'insert_task', 'manual__2023-01-28T07:43:54.790521+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpwt66105x']
[2023-01-28T07:44:26.944+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask insert_task
[2023-01-28T07:44:27.035+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV3.insert_task manual__2023-01-28T07:43:54.790521+00:00 [running]> on host 9763ece73850
[2023-01-28T07:44:27.118+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV3
AIRFLOW_CTX_TASK_ID=insert_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-28T07:43:54.790521+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-28T07:43:54.790521+00:00
[2023-01-28T07:44:27.119+0000] {sql.py:254} INFO - Executing: 
            insert into dag_runs(dt, dag_id) VALUES ('{ ds }', ' dag is dag not a dag')
        
[2023-01-28T07:44:27.137+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T07:44:27.488+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T07:44:27.506+0000] {sql.py:375} INFO - Running statement: 
            insert into dag_runs(dt, dag_id) VALUES ('{ ds }', ' dag is dag not a dag')
        , parameters: None
[2023-01-28T07:44:27.584+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date: "{ ds }"
LINE 2: ...         insert into dag_runs(dt, dag_id) VALUES ('{ ds }', ...
                                                             ^

[2023-01-28T07:44:27.834+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_second_dagV3, task_id=insert_task, execution_date=20230128T074354, start_date=20230128T074426, end_date=20230128T074427
[2023-01-28T07:44:27.924+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task insert_task (invalid input syntax for type date: "{ ds }"
LINE 2: ...         insert into dag_runs(dt, dag_id) VALUES ('{ ds }', ...
                                                             ^
; 5930)
[2023-01-28T07:44:27.974+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-28T07:44:27.990+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
