[2023-02-09T20:45:15.205+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV6.calculate_optimal_prices manual__2023-02-09T20:43:59.366928+00:00 [queued]>
[2023-02-09T20:45:15.213+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV6.calculate_optimal_prices manual__2023-02-09T20:43:59.366928+00:00 [queued]>
[2023-02-09T20:45:15.213+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T20:45:15.214+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-02-09T20:45:15.214+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T20:45:15.369+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): calculate_optimal_prices> on 2023-02-09 20:43:59.366928+00:00
[2023-02-09T20:45:15.373+0000] {standard_task_runner.py:55} INFO - Started process 20174 to run task
[2023-02-09T20:45:15.376+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV6', 'calculate_optimal_prices', 'manual__2023-02-09T20:43:59.366928+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpqlf91zri']
[2023-02-09T20:45:15.376+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask calculate_optimal_prices
[2023-02-09T20:45:15.895+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV6.calculate_optimal_prices manual__2023-02-09T20:43:59.366928+00:00 [running]> on host 47e55e08a495
[2023-02-09T20:45:15.997+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV6
AIRFLOW_CTX_TASK_ID=calculate_optimal_prices
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T20:43:59.366928+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-09T20:43:59.366928+00:00
[2023-02-09T20:45:15.998+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag2.py", line 21, in _calculate_optimal_prices
    with open("/sql/insert.sql", "x") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/sql/insert.sql'
[2023-02-09T20:45:16.005+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_second_dagV6, task_id=calculate_optimal_prices, execution_date=20230209T204359, start_date=20230209T204515, end_date=20230209T204516
[2023-02-09T20:45:16.016+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task calculate_optimal_prices ([Errno 2] No such file or directory: '/sql/insert.sql'; 20174)
[2023-02-09T20:45:16.035+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-09T20:45:16.068+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
